server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy API Requests to Backend
    location /api/ {
        proxy_pass http://backend:5001;
    }

    # Proxy Socket.io Requests to Backend
    location /socket.io/ {
        proxy_pass http://backend:5001;
    }

    # Serve Static Files and Support SPA Routing
    location / {
        try_files $uri $uri/ /index.html;
    }

}
